version: '2'
services:
    jhipstersampleapplicationng2sass-app:
        image: jhipstersampleapplicationng2sass
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationng2sass-mysql:3306/jhipstersampleapplicationng2sass?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationng2sass-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationng2sass-mysql
